Story.create
Story.create
Story.create
Story.create


User.create(name: "Nick", email:"user_1@mail.com", image:"/uploads/user_images/user_1.jpeg")
User.create(name: "Cute Puppy", email:"user_2@mail.com", image:"/uploads/user_images/user_2.jpeg")
User.create(name: "Donald", email:"user_3@mail.com", image:"/uploads/user_images/user_3.jpeg")
User.create(name: "Oprah", email:"user_4@mail.com", image:"/uploads/user_images/user_4.jpeg")
User.create(name: "Ron", email:"user_5@mail.com", image:"/uploads/user_images/user_5.jpeg")
User.create(name: "Eric", email:"user_6@mail.com", image:"/uploads/user_images/user_6.jpeg")
User.create(name: "Witch Bey", email:"user_7@mail.com", image:"/uploads/user_images/user_7.jpeg")
User.create(name: "Justin", email:"user_8@mail.com", image:"/uploads/user_images/user_8.jpeg")
User.create(name: "Winking Vlad", email:"user_9@mail.com", image:"/uploads/user_images/user_9.jpeg")
User.create(name: "Dreamboat", email:"user_10@mail.com", image:"/uploads/user_images/user_10.jpeg")
User.create(name: "AfroDude?", email:"user_11@mail.com", image:"/uploads/user_images/user_11.jpeg")
User.create(name: "Uncle Saul", email:"user_12@mail.com", image:"/uploads/user_images/user_12.jpeg")
User.create(name: "user_13", email:"user_13@mail.com", image:"/uploads/user_images/user_13.jpeg")
User.create(name: "user_14", email:"user_14@mail.com", image:"/uploads/user_images/user_14.jpeg")

Input.create(story_id: 1, user_id: 1, type: "Text", caption: "Superman. If superman was a colorful mushroom with spots and fake yellow cartoon hands.", image_path: nil)
Input.create(story_id: 1, user_id: 3, type: "Text", caption: "Psychedelic Mushroom Superhero", image_path: nil)
Input.create(story_id: 1, user_id: 5, type: "Text", caption: "My daily dosage on an average Wednesday.", image_path: nil)
Input.create(story_id: 1, user_id: 7, type: "Text", caption: "Consequences of a wild Tuesday.", image_path: nil)
Input.create(story_id: 1, user_id: 9, type: "Text", caption: "A sad, confused man wakes up naked after blacking out.", image_path: nil)
Input.create(story_id: 1, user_id: 11, type: "Text", caption: "A stick figure gets roofied and wakes up naked on a futon outside.", image_path: nil)
Input.create(story_id: 2, user_id: 2, type: "Text", caption: "Lighthouse Labs", image_path: nil)
Input.create(story_id: 2, user_id: 4, type: "Text", caption: "A striped robot in a pointy hat plays on a computer with its TREX arms while a flying red droid looks on.", image_path: nil)
Input.create(story_id: 2, user_id: 6, type: "Text", caption: "Misfit animals binge game.", image_path: nil)
Input.create(story_id: 2, user_id: 8, type: "Text", caption: "A boss squirrel loves junk food and gaming.", image_path: nil)
Input.create(story_id: 2, user_id: 10, type: "Text", caption: "A multitasking squirrel eats pizza while playing NES. In a headset.", image_path: nil)
Input.create(story_id: 2, user_id: 12, type: "Text", caption: "A hungry squirrel in a baseball cap takes his zelda way too seriously.", image_path: nil)
Input.create(story_id: 3, user_id: 3, type: "Text", caption: "A wall to keep out the Mexicans. Courtesy of TRUMP.", image_path: nil)
Input.create(story_id: 3, user_id: 5, type: "Text", caption: "A massive adobe brick asteroid destroys the entire Southwest US and its population.", image_path: nil)
Input.create(story_id: 3, user_id: 7, type: "Text", caption: "A giant flaming brick flies into California", image_path: nil)
Input.create(story_id: 3, user_id: 9, type: "Text", caption: "A box of fire flying straight into a bridge. Look. Out.", image_path: nil)
Input.create(story_id: 3, user_id: 11, type: "Text", caption: "An escape route from a burning house over a bridge.", image_path: nil)
Input.create(story_id: 3, user_id: 1, type: "Text", caption: "Oh No! The house is on fire! Good thing we have this sweet waterslide!", image_path: nil)
Input.create(story_id: 4, user_id: 2, type: "Text", caption: "How many licks does it take to get to the center of a tootsie roll pop?", image_path: nil)
Input.create(story_id: 4, user_id: 11, type: "Text", caption: "Koolaid Man can't figure out what flavor a lollipop is. Or what flavor he is.", image_path: nil)
Input.create(story_id: 1, user_id: 2, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_2_story_id_1_user_id_2.png")
Input.create(story_id: 1, user_id: 4, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_7_story_id_1_user_id_4.png")
Input.create(story_id: 1, user_id: 6, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_13_story_id_1_user_id_6.png")
Input.create(story_id: 1, user_id: 8, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_19_story_id_1_user_id_8.png")
Input.create(story_id: 1, user_id: 10, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_25_story_id_1_user_id_10.png")
Input.create(story_id: 1, user_id: 12, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_31_story_id_1_user_id_12.png")
Input.create(story_id: 2, user_id: 3, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_5_story_id_2_user_id_3.png")
Input.create(story_id: 2, user_id: 5, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_11_story_id_2_user_id_5.png")
Input.create(story_id: 2, user_id: 7, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_17_story_id_2_user_id_7.png")
Input.create(story_id: 2, user_id: 9, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_23_story_id_2_user_id_9.png")
Input.create(story_id: 2, user_id: 11, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_29_story_id_2_user_id_11.png")
Input.create(story_id: 2, user_id: 1, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_34_story_id_2_user_id_1.png")
Input.create(story_id: 3, user_id: 4, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_9_story_id_3_user_id_4.png")
Input.create(story_id: 3, user_id: 6, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_15_story_id_3_user_id_6.png")
Input.create(story_id: 3, user_id: 8, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_21_story_id_3_user_id_8.png")
Input.create(story_id: 3, user_id: 10, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_27_story_id_3_user_id_10.png")
Input.create(story_id: 3, user_id: 12, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_33_story_id_3_user_id_12.png")
Input.create(story_id: 3, user_id: 2, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_36_story_id_3_user_id_2.png")
Input.create(story_id: 4, user_id: 6, type: "Image", caption: nil, image_path:"uploads/seed_drawings/image_id_38_story_id_4_user_id_6.png")



